export interface imgItem{
  img:Resource
  title:string
  price:string
  sold:string
}

export const MemberItemList:Array<imgItem> = [
  {
    img: $r('app.media.my_huiyuan_mall1'),
    title:"车主专享满5元享5折10元封顶指定线下商户立减券",
    price:'198',
    sold:'3000'
  },
  {
    img: $r('app.media.my_huiyuan_mall2'),
    title:"连续包月首月1.99元 限时抢购62会员",
    price:'699',
    sold:'30万'
  },
  {
    img: $r('app.media.my_huiyuan_mall3'),
    title:"10元商超便利店潮玩立减券（2张满45减5元指定线下商户立减券）",
    price:'299',
    sold:'9000'
  },
  {
    img: $r('app.media.my_huiyuan_mall4'),
    title:"62VIP专属淘宝指定商户满30元享受8折优惠封顶6.2元",
    price:'149',
    sold:'5000'
  },
  {
    img: $r('app.media.my_huiyuan_mall5'),
    title:"线上缤纷迎新惠-满50减9.9元立减券",
    price:'1499',
    sold:'20万'
  },
  {
    img: $r('app.media.my_huiyuan_mall6'),
    title:"5折购62VIP季卡立减券",
    price:'709',
    sold:'40万'
  },
  {
    img: $r('app.media.my_huiyuan_mall7'),
    title:"点击查询申卡和奖励发放进度",
    price:'669',
    sold:'800'
  },
  {
    img: $r('app.media.my_huiyuan_mall8'),
    title:"满10减1元微信小程序立减券",
    price:'280',
    sold:'3000'
  },
  // {
  //   img: $r('app.media.ic_recommend8'),
  //   title:"德国supkit气压式热水瓶家用按压式保温大容量热水壶暖瓶保温暖壶",
  //   price:'399',
  //   sold:'5000'
  // },
  // {
  //   img: $r('app.media.ic_recommend9'),
  //   title:"天堂伞防晒防紫外线太阳伞轻小巧便携折叠晴雨两用伞女男士遮阳伞",
  //   price:'38.9',
  //   sold:'9000'
  // },
  // {
  //   img: $r('app.media.ic_recommend10'),
  //   title:"【百亿补贴】海狸先生黄鱼酥即食香酥小黄花鱼零食即食鱼仔小鱼干",
  //   price:'39.9',
  //   sold:'1万'
  // },
  // {
  //   img: $r('app.media.ic_recommend1'),
  //   title:"珀莱雅红宝石面霜3.0双环肽抗皱紧致淡纹",
  //   price:'699',
  //   sold:'30万'
  // },
  // {
  //   img: $r('app.media.ic_recommend2'),
  //   title:"海吉尔即食羊栖菜温州洞头特产东海长寿菜即食海藻丝海草凉菜榨菜",
  //   price:'299',
  //   sold:'9000'
  // },
  // {
  //   img: $r('app.media.ic_recommend3'),
  //   title:"【百亿补贴】YvesSaintLaurent/圣罗兰ysl小金条唇膏",
  //   price:'149',
  //   sold:'5000'
  // },
  // {
  //   img: $r('app.media.ic_recommend4'),
  //   title:"台湾常春淡奶油1L 植物性鲜奶油打发奶盖家用烘焙蛋糕裱花专用",
  //   price:'69.9',
  //   sold:'20万'
  // },
  // {
  //   img: $r('app.media.ic_recommend5'),
  //   title:"上海特产老城隍庙奶油味五香豆 茴香豆 五香蚕豆200g*3/5袋",
  //   price:'19.8',
  //   sold:'40万'
  // },
  // {
  //   img: $r('app.media.ic_recommend6'),
  //   title:"Petrus柏翠复古咖啡机家用小型半自动意式萃取浓缩商用蒸汽打奶泡",
  //   price:'669',
  //   sold:'800'
  // },
  // {
  //   img: $r('app.media.ic_recommend7'),
  //   title:"凯瑞kiri奶油奶酪200g小包装进口芝士块慕斯乳酪蛋糕烘焙材料家用",
  //   price:'280',
  //   sold:'3000'
  // },
  // {
  //   img: $r('app.media.ic_recommend8'),
  //   title:"德国supkit气压式热水瓶家用按压式保温大容量热水壶暖瓶保温暖壶",
  //   price:'399',
  //   sold:'5000'
  // },
  // {
  //   img: $r('app.media.ic_recommend9'),
  //   title:"天堂伞防晒防紫外线太阳伞轻小巧便携折叠晴雨两用伞女男士遮阳伞",
  //   price:'38.9',
  //   sold:'9000'
  // },
  // {
  //   img: $r('app.media.ic_recommend10'),
  //   title:"【百亿补贴】海狸先生黄鱼酥即食香酥小黄花鱼零食即食鱼仔小鱼干",
  //   price:'39.9',
  //   sold:'1万'
  // },
  // {
  //   img: $r('app.media.ic_recommend1'),
  //   title:"珀莱雅红宝石面霜3.0双环肽抗皱紧致淡纹",
  //   price:'699',
  //   sold:'30万'
  // },
  // {
  //   img: $r('app.media.ic_recommend2'),
  //   title:"海吉尔即食羊栖菜温州洞头特产东海长寿菜即食海藻丝海草凉菜榨菜",
  //   price:'299',
  //   sold:'9000'
  // },
  // {
  //   img: $r('app.media.ic_recommend3'),
  //   title:"【百亿补贴】YvesSaintLaurent/圣罗兰ysl小金条唇膏",
  //   price:'149',
  //   sold:'5000'
  // },
  // {
  //   img: $r('app.media.ic_recommend4'),
  //   title:"台湾常春淡奶油1L 植物性鲜奶油打发奶盖家用烘焙蛋糕裱花专用",
  //   price:'69.9',
  //   sold:'20万'
  // },
  // {
  //   img: $r('app.media.ic_recommend5'),
  //   title:"上海特产老城隍庙奶油味五香豆 茴香豆 五香蚕豆200g*3/5袋",
  //   price:'19.8',
  //   sold:'40万'
  // },
  // {
  //   img: $r('app.media.ic_recommend6'),
  //   title:"Petrus柏翠复古咖啡机家用小型半自动意式萃取浓缩商用蒸汽打奶泡",
  //   price:'669',
  //   sold:'800'
  // },
  // {
  //   img: $r('app.media.ic_recommend7'),
  //   title:"凯瑞kiri奶油奶酪200g小包装进口芝士块慕斯乳酪蛋糕烘焙材料家用",
  //   price:'280',
  //   sold:'3000'
  // },
  // {
  //   img: $r('app.media.ic_recommend8'),
  //   title:"德国supkit气压式热水瓶家用按压式保温大容量热水壶暖瓶保温暖壶",
  //   price:'399',
  //   sold:'5000'
  // },
  // {
  //   img: $r('app.media.ic_recommend9'),
  //   title:"天堂伞防晒防紫外线太阳伞轻小巧便携折叠晴雨两用伞女男士遮阳伞",
  //   price:'38.9',
  //   sold:'9000'
  // },
  // {
  //   img: $r('app.media.ic_recommend10'),
  //   title:"【百亿补贴】海狸先生黄鱼酥即食香酥小黄花鱼零食即食鱼仔小鱼干",
  //   price:'39.9',
  //   sold:'1万'
  // }
]